name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, windows-2022, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin,x86_64-pc-windows-msvc,x86_64-unknown-linux-gnu

      - uses: actions/setup-node@v4
        with:
          node-version: 20
        

      - name: Install Linux build deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install create-dmg (macOS)
        if: runner.os == 'macOS'
        run: brew install create-dmg

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm@8
          cd gui
          pnpm install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: gui
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: List bundle contents
        run: ls -R gui/target || true

      # Upload artifacts for every successful build (branch or tag)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-bundles
          path: |
            gui/target/**/bundle/**

      - name: Upload artifacts to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            **/bundle/**/*.dmg
            **/bundle/**/*.msi
            **/bundle/**/*.AppImage
            **/bundle/**/*.{zip,tar.gz}
