name: Windows CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensure full history so we checkout the exact latest commit
      - name: Show checked-out commit
        run: git --no-pager log -1 --oneline
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Cache cargo registry + target dir
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # Configure environment for static linking
      - name: Setup environment variables
        run: echo "RUSTFLAGS=-Ctarget-feature=+crt-static" >> $env:GITHUB_ENV

      - name: Build (debug)
        run: cargo build --verbose
      # Skip tests on Windows due to side-by-side configuration issues
      # See: https://github.com/microsoft/vcpkg/issues/4
      - name: Skip tests on Windows
        run: echo "Skipping tests on Windows due to side-by-side configuration issues"
      - name: Install Node.js for GUI build
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Disable npm cache to avoid conflicts
          # cache: 'npm'
          # cache-dependency-path: gui/package-lock.json

      - name: Clear npm cache
        working-directory: gui
        run: npm cache clean --force
        
      - name: Install GUI dependencies
        working-directory: gui
        run: npm install

      - name: Build (release) CLI
        run: cargo build --release --verbose

      - name: Build GUI (Tauri)
        working-directory: gui
        run: npm run tauri build

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Prepare unified package
        run: |
          # Create package directory with CLI and GUI
          New-Item -ItemType Directory -Force -Path package
          Copy-Item "target/release/blitzarch.exe" -Destination "package/"
          
          # Copy GUI if exists
          $GuiPath = "gui/src-tauri/target/release/bundle/msi/BlitzArch_*_x64_en-US.msi"
          $GuiFiles = Get-ChildItem -Path $GuiPath -ErrorAction SilentlyContinue
          if ($GuiFiles) {
            Copy-Item $GuiFiles[0].FullName -Destination "package/BlitzArch-GUI.msi"
            Write-Host "✅ GUI installer found and included"
          } else {
            Write-Host "⚠️  GUI installer not found, CLI-only package"
          }
        shell: pwsh

      - name: Package unified MSI
        run: |
          $env:PATH = "C:\Program Files (x86)\WiX Toolset v3.11\bin;$env:PATH"
          # Check if build_msi.bat exists, if so use it, otherwise use direct candle/light commands
          if (Test-Path -Path "./installer/build_msi.bat") {
            ./installer/build_msi.bat
          } else {
            candle installer/blitzarch.wxs -o installer/blitzarch.wixobj
            light -ext WixUIExtension installer/blitzarch.wixobj -o BlitzArch.msi
          }
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: BlitzArch-MSI
          path: BlitzArch.msi

      - name: Upload unified package
        uses: actions/upload-artifact@v4
        with:
          name: BlitzArch-Windows-Package
          path: package/
