name: Windows CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensure full history so we checkout the exact latest commit
      - name: Show checked-out commit
        run: git --no-pager log -1 --oneline
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Cache cargo registry + target dir
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # Configure environment for static linking
      - name: Setup environment variables
        run: echo "RUSTFLAGS=-Ctarget-feature=+crt-static" >> $env:GITHUB_ENV

      - name: Build (debug)
        run: cargo build --verbose
      # Skip tests on Windows due to side-by-side configuration issues
      # See: https://github.com/microsoft/vcpkg/issues/4
      - name: Skip tests on Windows
        run: echo "Skipping tests on Windows due to side-by-side configuration issues"
      - name: Build (release)
        run: cargo build --release --verbose

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Package MSI
        run: |
          $env:PATH = "C:\Program Files (x86)\WiX Toolset v3.11\bin;$env:PATH"
          # Check if build_msi.bat exists, if so use it, otherwise use direct candle/light commands
          if (Test-Path -Path "./installer/build_msi.bat") {
            ./installer/build_msi.bat
          } else {
            candle installer/blitzarch.wxs -o installer/blitzarch.wixobj
            light -ext WixUIExtension installer/blitzarch.wixobj -o BlitzArch.msi
          }
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: BlitzArch-MSI
          path: BlitzArch.msi
