name: Windows CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensure full history so we checkout the exact latest commit
      - name: Show checked-out commit
        run: git --no-pager log -1 --oneline
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Cache cargo registry + target dir
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build (debug)
        run: cargo build --verbose
      - name: Setup Rust for static linking
        run: |
          # Configure Rust to use the MSVC static CRT
          New-Item -Path $env:USERPROFILE\.cargo -ItemType Directory -Force
          Set-Content -Path $env:USERPROFILE\.cargo\config.toml -Value "[target.x86_64-pc-windows-msvc]`nrustflags = [`"-Ctarget-feature=+crt-static`"]"
          cat $env:USERPROFILE\.cargo\config.toml
      - name: Run tests
        run: cargo test --all --verbose
      - name: Build (release)
        run: cargo build --release --verbose

      - name: Install WiX Toolset
        run: choco install wix -y

      - name: Package MSI
        run: |
          PATH="C:\Program Files (x86)\WiX Toolset v3.11\bin;$PATH"
          candle installer/blitzarch.wxs -o installer/blitzarch.wixobj
          light -ext WixUIExtension installer/blitzarch.wixobj -o BlitzArch.msi

      - uses: actions/upload-artifact@v4
        with:
          name: BlitzArch-MSI
          path: BlitzArch.msi
